### PR TITLE
Simplify "Mocking instanciation" with mock

### PR DESCRIPTION
**Pull request by JocelynDelalande**
This change is iso-functional.

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
@garybernhardt bump ?

**Comment by garybernhardt** [comment]
Did you run the doctests with tox to make sure that everything is still good on various Python versions?

**Comment by JocelynDelalande** [comment]
@garybernhardt they are not passing on master, so it's hard to say ;-).

Are they failling for you also or is it me ?

**Comment by garybernhardt** [comment]
It definitely worked at one point. Unfortunately, locking dependency versions wasn't common in Python back then and I didn't do it. As a result, we have no way to know which versions of the libraries are actually specified here.

If you're feeling ambitious, I'll happily accept a PR that brings everything up to date and gets the doctests passing again, perhaps removing libraries whose PyPI download numbers are near zero. I don't want to spend the time to update everything myself so, unless someone steps up, I think that the whole project should be clearly marked as abandoned. Judging by PyPI download counts, mock has thoroughly won anyway (and rightfully so: it's a good API, despite its name being incorrect. ;)

**Comment by JocelynDelalande** [comment]
Ok, thanks for taking time to answer :)

I do not want to take that much time :-), so either you accept the PR as-is, either I close it.

**Pull request closed without merging**
